using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using NUnit.Framework;
using Colyseus;
using Colyseus.Schema;

namespace SchemaTest.Input
{
	// Hand-written fixture matching colyseus-0.18
	// PORTING/generate-input-fixtures.cts (MoveInput) — field order is the
	// wire contract.
	public class MoveInput : Colyseus.Schema.Schema
	{
		[Colyseus.Schema.Type(0, "number")]
		public float vx;

		[Colyseus.Schema.Type(1, "number")]
		public float vy;

		[Colyseus.Schema.Type(2, "boolean")]
		public bool jump;

		[Colyseus.Schema.Type(3, "uint8")]
		public byte action;
	}
}

namespace Colyseus.Tests
{
	/// <summary>
	///     Phase 3 — input layer + RoomClock.
	///
	///     Fixtures generated by colyseus-0.18
	///     PORTING/generate-input-fixtures.cts (self-verified against the JS
	///     schema InputEncoder/InputDecoder, the real InputHandleImpl and
	///     RoomClockImpl). Contract: PORTING/sdk-ports-input-layer.md.
	/// </summary>
	[TestFixture]
	public class InputTest
	{
		private class StubConnection : Connection
		{
			public readonly List<byte[]> Sent = new List<byte[]>();

			public StubConnection() : base("ws://localhost", null)
			{
				IsOpen = true;
			}

			public override Task Send(byte[] data)
			{
				Sent.Add((byte[])data.Clone());
				return Task.CompletedTask;
			}
		}

		private class StubClock : RoomClock
		{
			public double ServerNowValue;
			public double LastServerTimeValue;
			public double SmoothedRttValue;

			public override double ServerNow() => ServerNowValue;
			public override double LastServerTime() => LastServerTimeValue;
			public override double SmoothedRtt() => SmoothedRttValue;
		}

		private static (InputHandle handle, StubConnection stub, SchemaTest.Input.MoveInput input) MakeHandle(
			RoomClock clock, string mode = "reliable",
			bool stampRender = false, bool stampReckon = false,
			double renderDelay = 0, Func<object, bool> allowRewind = null)
		{
			var input = new SchemaTest.Input.MoveInput();
			var encoder = new InputEncoder(input, mode, 3);
			var stub = new StubConnection();
			var handle = new InputHandle(
				input, encoder, stampRender, stampReckon, renderDelay, allowRewind,
				null, null, null, () => stub, () => clock);
			return (handle, stub, input);
		}

		[Test]
		public void InputEncoderReliableTest()
		{
			var input = new SchemaTest.Input.MoveInput();
			var encoder = new InputEncoder(input);

			input.vx = 1.5f; input.vy = -2; input.jump = true; input.action = 3;
			CollectionAssert.AreEqual(new byte[] { 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3 }, encoder.Encode());

			input.vx = 2.5f;
			CollectionAssert.AreEqual(new byte[] { 128, 202, 0, 0, 32, 64 }, encoder.Encode());

			// no change → empty body
			CollectionAssert.AreEqual(new byte[] { }, encoder.Encode());

			input.jump = false; input.action = 7;
			CollectionAssert.AreEqual(new byte[] { 130, 0, 131, 7 }, encoder.Encode());

			// reset → full snapshot of populated fields
			encoder.Reset();
			CollectionAssert.AreEqual(new byte[] { 128, 202, 0, 0, 32, 64, 129, 254, 130, 0, 131, 7 }, encoder.Encode());
		}

		[Test]
		public void InputEncoderUnreliableTest()
		{
			var input = new SchemaTest.Input.MoveInput();
			var encoder = new InputEncoder(input, "unreliable", 3);

			input.vx = 1.5f; input.vy = -2; input.jump = true; input.action = 3;
			CollectionAssert.AreEqual(new byte[] { 1, 12, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3 }, encoder.Encode());
			Assert.AreEqual(1, encoder.Seq);

			input.vx = 2.5f;
			CollectionAssert.AreEqual(new byte[] { 1, 12, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3, 6, 128, 202, 0, 0, 32, 64 }, encoder.Encode());

			// no change → carry-forward empty slot, ring re-emitted
			CollectionAssert.AreEqual(new byte[] { 1, 12, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3, 6, 128, 202, 0, 0, 32, 64, 0 }, encoder.Encode());

			input.vy = 9;
			CollectionAssert.AreEqual(new byte[] { 2, 6, 128, 202, 0, 0, 32, 64, 0, 2, 129, 9 }, encoder.Encode());
			Assert.AreEqual(4, encoder.Seq);
		}

		[Test]
		public void HandleReliableNoStampTest()
		{
			var (handle, stub, input) = MakeHandle(new StubClock());

			input.vx = 1.5f; input.vy = -2; input.jump = true; input.action = 3;
			Assert.AreEqual(1, handle.Send());
			input.vx = 2.5f;
			Assert.AreEqual(2, handle.Send());
			Assert.AreEqual(3, handle.Send()); // no change → body-less [19]

			Assert.AreEqual(3, handle.SentCount);
			CollectionAssert.AreEqual(new byte[] { 19, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3 }, stub.Sent[0]);
			CollectionAssert.AreEqual(new byte[] { 19, 128, 202, 0, 0, 32, 64 }, stub.Sent[1]);
			CollectionAssert.AreEqual(new byte[] { 19 }, stub.Sent[2]);
		}

		[Test]
		public void HandleReliableStampedBothTest()
		{
			var clock = new StubClock { LastServerTimeValue = 500, SmoothedRttValue = 80 };
			var (handle, stub, input) = MakeHandle(clock, stampRender: true, stampReckon: true, renderDelay: 50);

			clock.ServerNowValue = 1000;
			input.vx = 1.5f;
			handle.Send();
			clock.ServerNowValue = 1016.7;
			input.vx = 2;
			handle.Send();
			clock.ServerNowValue = 1033.4;
			handle.Send();

			// [19|0x80][varint Δreckon][uint16 renderDelta=90][delta body]
			CollectionAssert.AreEqual(new byte[] { 147, 205, 232, 3, 90, 0, 128, 202, 0, 0, 192, 63 }, stub.Sent[0]);
			CollectionAssert.AreEqual(new byte[] { 147, 17, 90, 0, 128, 2 }, stub.Sent[1]);
			CollectionAssert.AreEqual(new byte[] { 147, 16, 90, 0 }, stub.Sent[2]);

			Assert.AreEqual(1000, handle.ReckonTimeAt(1));
			Assert.AreEqual(1017, handle.ReckonTimeAt(2));
			Assert.AreEqual(1033, handle.ReckonTimeAt(3));
		}

		[Test]
		public void HandleReliableStampedRenderOnlyTest()
		{
			var clock = new StubClock { LastServerTimeValue = 500, SmoothedRttValue = 80 };
			var (handle, stub, input) = MakeHandle(clock, stampRender: true, renderDelay: 50);

			clock.ServerNowValue = 1000;
			input.vx = 1.5f;
			handle.Send();     // stamp = 1000-90 = 910
			clock.ServerNowValue = 1050;
			input.vx = 2;
			handle.Send();     // Δ = 50

			CollectionAssert.AreEqual(new byte[] { 147, 205, 142, 3, 128, 202, 0, 0, 192, 63 }, stub.Sent[0]);
			CollectionAssert.AreEqual(new byte[] { 147, 50, 128, 2 }, stub.Sent[1]);
			Assert.AreEqual(0, handle.ReckonTimeAt(1)); // reckon ring off
		}

		[Test]
		public void HandleUnstampedBeforeSyncTest()
		{
			var clock = new StubClock { ServerNowValue = 1234, LastServerTimeValue = 0, SmoothedRttValue = 80 };
			var (handle, stub, input) = MakeHandle(clock, stampRender: true, stampReckon: true);

			input.vx = 1;
			handle.Send();
			CollectionAssert.AreEqual(new byte[] { 147, 0, 0, 0, 128, 1 }, stub.Sent[0]);
		}

		[Test]
		public void HandleAllowRewindGateTest()
		{
			var clock = new StubClock { LastServerTimeValue = 500 };
			var (handle, stub, input) = MakeHandle(clock, stampReckon: true,
				allowRewind: d => ((SchemaTest.Input.MoveInput)d).jump);

			clock.ServerNowValue = 1000;
			input.vx = 1;
			handle.Send();                     // unstamped (jump=false at default)
			clock.ServerNowValue = 1100;
			input.jump = true;
			handle.Send();                     // stamped, Δ=1100
			clock.ServerNowValue = 1200;
			input.jump = false;
			handle.Send();                     // unstamped (baseline holds)
			clock.ServerNowValue = 1300;
			input.jump = true;
			handle.Send();                     // stamped, Δ=200

			CollectionAssert.AreEqual(new byte[] { 19, 128, 1 }, stub.Sent[0]);
			CollectionAssert.AreEqual(new byte[] { 147, 205, 76, 4, 130, 1 }, stub.Sent[1]);
			CollectionAssert.AreEqual(new byte[] { 19, 130, 0 }, stub.Sent[2]);
			CollectionAssert.AreEqual(new byte[] { 147, 204, 200, 130, 1 }, stub.Sent[3]);
		}

		[Test]
		public void HandleUnreliableTest()
		{
			var clock = new StubClock { LastServerTimeValue = 500 };
			var (handle, stub, input) = MakeHandle(clock, mode: "unreliable", stampReckon: true);

			input.vx = 1.5f;
			Assert.AreEqual(1, handle.Send());
			input.vx = 2.5f;
			Assert.AreEqual(2, handle.Send());
			Assert.AreEqual(2, handle.SentCount);

			// [20][baseSeq][len][slot]… — unreliable is never stamped
			CollectionAssert.AreEqual(new byte[] { 20, 1, 6, 128, 202, 0, 0, 192, 63 }, stub.Sent[0]);
			CollectionAssert.AreEqual(new byte[] { 20, 1, 6, 128, 202, 0, 0, 192, 63, 6, 128, 202, 0, 0, 32, 64 }, stub.Sent[1]);
		}

		[Test]
		public void HandleAckRttTest()
		{
			double now = 0;
			var originalNow = RoomClock.GetNow;
			RoomClock.GetNow = () => now;

			try
			{
				var (handle, stub, input) = MakeHandle(new StubClock());

				now = 1000; input.vx = 1; handle.Send();
				now = 1016; input.vx = 2; handle.Send();
				now = 1033; input.vx = 3; handle.Send();

				now = 1080;
				Assert.AreEqual(80, handle.AckInput(1));
				Assert.AreEqual(-1, handle.AckInput(1)); // stale
				now = 1120;
				Assert.AreEqual(87, handle.AckInput(3)); // skips 2
				Assert.AreEqual(3, handle.LastProcessed);
				Assert.AreEqual(0, handle.PendingCount);

				// replay ring: pending inputs readable until acked
				now = 1200; input.vx = 4; handle.Send(); // seq 4
				Assert.AreEqual(4f, ((SchemaTest.Input.MoveInput)handle.At(4)).vx);
				Assert.IsNull(handle.At(3));             // acked → gone

				// reset: epoch++, fresh counters, next send = full snapshot
				int epochBefore = handle.Epoch;
				handle.Reset();
				Assert.AreEqual(epochBefore + 1, handle.Epoch);
				Assert.AreEqual(0, handle.SentCount);
				now = 1300; input.vx = 5;
				Assert.AreEqual(1, handle.Send());
				CollectionAssert.AreEqual(new byte[] { 19, 128, 5, 129, 0, 130, 0, 131, 0 }, stub.Sent[stub.Sent.Count - 1]);
				now = 1360;
				Assert.AreEqual(60, handle.AckInput(1));
			}
			finally
			{
				RoomClock.GetNow = originalNow;
			}
		}

		[Test]
		public void RoomClockSamplesTest()
		{
			double now = 0;
			var originalNow = RoomClock.GetNow;
			RoomClock.GetNow = () => now;

			try
			{
				var clock = new RoomClock();
				clock.SetPatchInterval(50);

				// (tNow, sNow, rtt) → (offset, rtt, smoothedRtt, jitter, lastServerTime)
				var script = new[]
				{
					new double[] { 1000, 500, -1,    -500, 0, 0, 0, 500 },
					new double[] { 1050, 550, 80,    -496, 80, 80, 0, 550 },
					new double[] { 1100, 600, 84,    -492.20000000000005, 84, 80.4, 0, 600 },
					new double[] { 1155, 655, 90,    -488.4800000000001, 90, 81.36000000000001, 0.3125, 655 },
					new double[] { 1205, 705, 76,    -485.83200000000005, 76, 80.82400000000001, 0.29296875, 705 },
					new double[] { 1305, 805, 82,    -483.14880000000005, 82, 80.94160000000002, 0.274658203125, 805 },
					new double[] { 1655, 1155, 78,   -480.93392000000006, 78, 80.64744000000002, 0.274658203125, 1155 },
					new double[] { 1705, 1205, 400,  -480.93392000000006, 78, 80.64744000000002, 0.2574920654296875, 1205 },
					new double[] { 1755, 1255, 74,   -479.1405280000001, 74, 79.98269600000002, 0.24139881134033203, 1255 },
				};
				foreach (var row in script)
				{
					now = row[0];
					clock.Sample(row[1], row[2]);
					Assert.AreEqual(row[3], clock._clockOffset);
					Assert.AreEqual(row[4], clock.Rtt());
					Assert.AreEqual(row[5], clock.SmoothedRtt());
					Assert.AreEqual(row[6], clock.Jitter());
					Assert.AreEqual(row[7], clock.LastServerTime());
				}

				now = 1800;
				Assert.AreEqual(1320.8594719999999, clock.ServerNow());

				// RenderNow — 1e-6 tolerance (exp() ULP variance across libms)
				now = 1800;
				double r1 = clock.RenderNow();
				now = 1816;
				double r2 = clock.RenderNow();
				now = 1816.2;
				double r3 = clock.RenderNow(); // same frame → unchanged
				Assert.AreEqual(1320.8594719999999, r1, 1e-6);
				Assert.AreEqual(1336.8594719999999, r2, 1e-6);
				Assert.AreEqual(r2, r3);

				// reset clears estimates; patch interval is config and survives
				clock.Reset();
				Assert.AreEqual(0, clock.SmoothedRtt());
				Assert.AreEqual(0, clock.LastServerTime());
				Assert.AreEqual(50, clock.PatchInterval());
			}
			finally
			{
				RoomClock.GetNow = originalNow;
			}
		}

		private class TestRoom : Room<SchemaTest.Phase0.P0State>
		{
			public TestRoom() : base("phase0")
			{
				RoomId = "phase0";
			}

			public void Feed(byte[] frame)
			{
				ParseMessage(frame);
			}
		}

		[Test]
		public void RoomInputOptionsAndTimedRoutingTest()
		{
			// JOIN_ROOM fixture with INPUT_REFLECTION + INPUT_OPTIONS sections
			// (flags FIXED|PATCH|SUB, tickRate 20, patchRate 50, subSteps 2) —
			// from PORTING/generate-phase0-fixtures.cts.
			var room = new TestRoom();
			var stub = new StubConnection();
			room.SetConnection(stub);

			room.Feed(new byte[] { 10, 6, 116, 111, 107, 49, 50, 51, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114, 1, 47, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 161, 120, 129, 166, 110, 117, 109, 98, 101, 114, 255, 5, 128, 161, 121, 129, 166, 110, 117, 109, 98, 101, 114, 2, 4, 14, 20, 50, 2 });

			Assert.AreEqual(50, room.Clock.PatchInterval());

			// no explicit type: the input schema is synthesized from
			// INPUT_REFLECTION as a DynamicSchema (server fields: x, y)
			var handle = room.Input();
			Assert.AreEqual(20, handle.TickRate);
			Assert.AreEqual(50, handle.PatchRate);
			Assert.AreEqual(2, handle.SubSteps);
			Assert.AreEqual(0.05, handle.StepSeconds);
			Assert.AreEqual(0.025, handle.SubStepSeconds);
			Assert.GreaterOrEqual(handle.ReplayBufferSize, 64);

			// same handle on later calls
			Assert.AreSame(handle, room.Input());

			var data = (DynamicSchema)handle.Data;
			data["x"] = 4.5f;
			data["y"] = 2f;
			int seq = handle.Send();
			Assert.AreEqual(1, seq);
			CollectionAssert.AreEqual(new byte[] { 19, 128, 202, 0, 0, 144, 64, 129, 2 }, stub.Sent[stub.Sent.Count - 1]);

			// TIMED heartbeat patch [15|0x80][u32 sNow=750][u32 inputSeq=0]
			room.Feed(new byte[] { 143, 238, 2, 0, 0, 0, 0, 0, 0 });
			Assert.AreEqual(750, room.Clock.LastServerTime());
		}

		[Test]
		public void RoomClockGateWarmupTest()
		{
			double now = 0;
			var originalNow = RoomClock.GetNow;
			RoomClock.GetNow = () => now;

			try
			{
				var clock = new RoomClock();
				clock.SetPatchInterval(50);
				double tNow = 1000;
				var expected = new Dictionary<int, double[]>
				{
					[5]  = new double[] { -341.855, 116.29 },
					[10] = new double[] { -332.85995895, 134.28008210000002 },
					[15] = new[] { -331.7339771603856, 136.53204567922904 },
					[20] = new[] { -326.88359617343616, 146.23280765312796 },
					[25] = new[] { -328.20499470445236, 143.59001059109553 },
					[30] = new[] { -324.79976732303214, 150.40046535393603 },
					[35] = new[] { -331.6290303784904, 146.0509707868457 },
				};
				for (int i = 1; i <= 35; i++)
				{
					tNow += 50;
					now = tNow;
					double rtt = i % 2 == 0 ? 200 : 100;
					clock.Sample(tNow - 400, rtt);
					if (expected.TryGetValue(i, out var want))
					{
						Assert.AreEqual(want[0], clock._clockOffset);
						Assert.AreEqual(want[1], clock.SmoothedRtt());
					}
				}
			}
			finally
			{
				RoomClock.GetNow = originalNow;
			}
		}
	}
}
