using NUnit.Framework;
using Colyseus.Schema;
using Colyseus.Schema.Utils;

namespace Colyseus.Tests
{
	/// <summary>
	///     A `"number"` carrying a float64 payload must not be narrowed to float32 when the destination
	///     field can hold it.
	/// </summary>
	/// <remarks>
	///     `"number"` is variable-width, and the encoder emits the 0xcb float64 prefix ONLY after testing
	///     that the value does not survive a float32 round trip - so a 0xcb on the wire is an assertion
	///     that float32 is insufficient. Decoding it as float discards up to 65536 ms of an epoch
	///     millisecond, silently.
	///
	///     The second half of this fixture is the more important one: a field declared `float` must still
	///     decode exactly as it did before, or the fix would be a breaking change for every schema
	///     generated by `schema-codegen --csharp`, which maps `"number"` to `float`.
	/// </remarks>
	[TestFixture]
	public class NumberPrecisionTest
	{
		/// <summary>A real epoch millisecond, well past float32's 24-bit mantissa.</summary>
		private const double EpochMs = 1786595532328d;

		/// <summary>The same bytes @colyseus/schema emits for a `"number"` needing float64.</summary>
		private static byte[] Float64Payload(double value)
		{
			var bytes = new byte[9];
			bytes[0] = 0xcb;
			System.BitConverter.GetBytes(value).CopyTo(bytes, 1);
			return bytes;
		}

		[Test]
		public void DecodesFloat64PayloadWithoutNarrowing()
		{
			byte[] bytes = Float64Payload(EpochMs);
			double decoded = Decode.DecodeNumberAsDouble(bytes, new Iterator { Offset = 0 });

			Assert.AreEqual(EpochMs, decoded, "a float64 payload must survive intact");
		}

		[Test]
		public void PrimitiveTypeDecodeHonoursADoubleDestination()
		{
			byte[] bytes = Float64Payload(EpochMs);
			object decoded = Decode.DecodePrimitiveType("number", bytes, new Iterator { Offset = 0 }, typeof(double));

			Assert.IsInstanceOf<double>(decoded);
			Assert.AreEqual(EpochMs, (double)decoded);
		}

		[Test]
		public void PrimitiveTypeDecodeIsUnchangedWithoutATargetType()
		{
			byte[] bytes = Float64Payload(EpochMs);

			object viaOldOverload = Decode.DecodePrimitiveType("number", bytes, new Iterator { Offset = 0 });
			object viaNullTarget = Decode.DecodePrimitiveType("number", bytes, new Iterator { Offset = 0 }, null);
			object viaFloatTarget = Decode.DecodePrimitiveType("number", bytes, new Iterator { Offset = 0 }, typeof(float));

			// Still a float, and still the SAME float - the existing behaviour is load-bearing for every
			// generated schema, where `"number"` fields are declared `float`.
			Assert.IsInstanceOf<float>(viaOldOverload);
			Assert.IsInstanceOf<float>(viaNullTarget);
			Assert.IsInstanceOf<float>(viaFloatTarget);
			Assert.AreEqual((float)EpochMs, (float)viaOldOverload);
			Assert.AreEqual((float)viaOldOverload, (float)viaNullTarget);
			Assert.AreEqual((float)viaOldOverload, (float)viaFloatTarget);
		}

		/// <summary>A schema with the same wire type reaching two different C# types.</summary>
		public class TimestampState : Schema.Schema
		{
			[Colyseus.Schema.Type(0, "number")]
			public double preciseAt = 0;

			[Colyseus.Schema.Type(1, "number")]
			public float legacyAt = 0;
		}

		/// <summary>
		///     The end-to-end path: the same bytes, into a `double` field and a `float` field.
		/// </summary>
		/// <remarks>
		///     This is the assertion that matters, because it goes through Decoder's field-type resolution
		///     rather than calling Decode directly. Both fields are declared `"number"` and receive an
		///     identical float64 payload; only the declared C# type differs.
		/// </remarks>
		[Test]
		public void DecoderGivesPrecisionToDoubleFieldsAndLeavesFloatFieldsAlone()
		{
			var decoder = new Colyseus.Schema.Decoder<TimestampState>();

			var bytes = new System.Collections.Generic.List<byte>();
			bytes.Add(0x80);                                    // field index 0 (preciseAt)
			bytes.AddRange(Float64Payload(EpochMs));
			bytes.Add(0x81);                                    // field index 1 (legacyAt)
			bytes.AddRange(Float64Payload(EpochMs));

			decoder.Decode(bytes.ToArray());

			Assert.AreEqual(EpochMs, decoder.State.preciseAt,
				"a `double` field must receive the float64 payload intact");
			Assert.AreEqual((float)EpochMs, decoder.State.legacyAt,
				"a `float` field must be exactly what it was before this change");
		}

		/// <summary>
		///     Every other prefix must be byte-for-byte identical on both paths, since the new one is only
		///     supposed to differ for 0xcb.
		/// </summary>
		[Test]
		public void NonFloat64PrefixesAreIdenticalOnBothPaths()
		{
			byte[][] payloads =
			{
				new byte[] { 0x7f },                                            // positive fixint
				new byte[] { 0xca, 0x00, 0x00, 0x80, 0x3f },                    // float32 1.0
				new byte[] { 0xcc, 0xff },                                      // uint8
				new byte[] { 0xcd, 0xff, 0xff },                                // uint16
				new byte[] { 0xce, 0xff, 0xff, 0xff, 0xff },                    // uint32
				new byte[] { 0xd0, 0x80 },                                      // int8
				new byte[] { 0xd1, 0x00, 0x80 },                                // int16
				new byte[] { 0xd2, 0x00, 0x00, 0x00, 0x80 },                    // int32
				new byte[] { 0xff },                                            // negative fixint
			};

			foreach (byte[] payload in payloads)
			{
				var itOld = new Iterator { Offset = 0 };
				var itNew = new Iterator { Offset = 0 };

				float viaNumber = Decode.DecodeNumber(payload, itOld);
				double viaDouble = Decode.DecodeNumberAsDouble(payload, itNew);

				Assert.AreEqual(viaNumber, viaDouble, "prefix 0x{0:x2} decoded differently", payload[0]);
				Assert.AreEqual(itOld.Offset, itNew.Offset, "prefix 0x{0:x2} consumed a different number of bytes", payload[0]);
			}
		}
	}
}
