using NUnit.Framework;
using Colyseus.Schema;
using Colyseus.Schema.Utils;

namespace Colyseus.Tests
{
	/// <summary>
	///     A `"number"` carrying a float64 payload must not be narrowed to float32 when the destination
	///     field can hold it.
	/// </summary>
	/// <remarks>
	///     `"number"` is variable-width, and the encoder emits the 0xcb float64 prefix ONLY after testing
	///     that the value does not survive a float32 round trip - so a 0xcb on the wire is an assertion
	///     that float32 is insufficient. Decoding it as float discards up to 65536 ms of an epoch
	///     millisecond, silently.
	///
	///     The second half of this fixture is the more important one: a field declared `float` must still
	///     decode exactly as it did before, or the fix would be a breaking change for every schema
	///     generated by `schema-codegen --csharp`, which maps `"number"` to `float`.
	/// </remarks>
	[TestFixture]
	public class NumberPrecisionTest
	{
		/// <summary>A real epoch millisecond, well past float32's 24-bit mantissa.</summary>
		private const double EpochMs = 1786595532328d;

		/// <summary>An integer `"number"` too big for float32 — an epoch millisecond sent as an int.</summary>
		private static byte[] Uint64Payload(ulong value)
		{
			var bytes = new byte[9];
			bytes[0] = 0xcf;
			System.BitConverter.GetBytes(value).CopyTo(bytes, 1);
			return bytes;
		}

		/// <summary>The same bytes @colyseus/schema emits for a `"number"` needing float64.</summary>
		private static byte[] Float64Payload(double value)
		{
			var bytes = new byte[9];
			bytes[0] = 0xcb;
			System.BitConverter.GetBytes(value).CopyTo(bytes, 1);
			return bytes;
		}

		[Test]
		public void DecodesFloat64PayloadWithoutNarrowing()
		{
			byte[] bytes = Float64Payload(EpochMs);
			double decoded = Decode.DecodeNumberAsDouble(bytes, new Iterator { Offset = 0 });

			Assert.AreEqual(EpochMs, decoded, "a float64 payload must survive intact");
		}

		[Test]
		public void PrimitiveTypeDecodeHonoursADoubleDestination()
		{
			byte[] bytes = Float64Payload(EpochMs);
			object decoded = Decode.DecodePrimitiveType("number", bytes, new Iterator { Offset = 0 }, typeof(double));

			Assert.IsInstanceOf<double>(decoded);
			Assert.AreEqual(EpochMs, (double)decoded);
		}

		[Test]
		public void PrimitiveTypeDecodeIsUnchangedWithoutATargetType()
		{
			byte[] bytes = Float64Payload(EpochMs);

			object viaOldOverload = Decode.DecodePrimitiveType("number", bytes, new Iterator { Offset = 0 });
			object viaNullTarget = Decode.DecodePrimitiveType("number", bytes, new Iterator { Offset = 0 }, null);
			object viaFloatTarget = Decode.DecodePrimitiveType("number", bytes, new Iterator { Offset = 0 }, typeof(float));

			// Still a float, and still the SAME float - the existing behaviour is load-bearing for every
			// generated schema, where `"number"` fields are declared `float`.
			Assert.IsInstanceOf<float>(viaOldOverload);
			Assert.IsInstanceOf<float>(viaNullTarget);
			Assert.IsInstanceOf<float>(viaFloatTarget);
			Assert.AreEqual((float)EpochMs, (float)viaOldOverload);
			Assert.AreEqual((float)viaOldOverload, (float)viaNullTarget);
			Assert.AreEqual((float)viaOldOverload, (float)viaFloatTarget);
		}

		/// <summary>A schema with the same wire type reaching two different C# types.</summary>
		public class TimestampState : Schema.Schema
		{
			[Colyseus.Schema.Type(0, "number")]
			public double preciseAt = 0;

			[Colyseus.Schema.Type(1, "number")]
			public float legacyAt = 0;
		}

		/// <summary>
		///     The end-to-end path: the same bytes, into a `double` field and a `float` field.
		/// </summary>
		/// <remarks>
		///     This is the assertion that matters, because it goes through Decoder's field-type resolution
		///     rather than calling Decode directly. Both fields are declared `"number"` and receive an
		///     identical float64 payload; only the declared C# type differs.
		/// </remarks>
		[Test]
		public void DecoderGivesPrecisionToDoubleFieldsAndLeavesFloatFieldsAlone()
		{
			var decoder = new Colyseus.Schema.Decoder<TimestampState>();

			var bytes = new System.Collections.Generic.List<byte>();
			bytes.Add(0x80);                                    // field index 0 (preciseAt)
			bytes.AddRange(Float64Payload(EpochMs));
			bytes.Add(0x81);                                    // field index 1 (legacyAt)
			bytes.AddRange(Float64Payload(EpochMs));

			decoder.Decode(bytes.ToArray());

			Assert.AreEqual(EpochMs, decoder.State.preciseAt,
				"a `double` field must receive the float64 payload intact");
			Assert.AreEqual((float)EpochMs, decoder.State.legacyAt,
				"a `float` field must be exactly what it was before this change");
		}

		/// <summary>
		///     The prefix ladder at both widths: the wide read is exact, the narrow one is that same value
		///     as a float, and each consumes its whole payload and nothing more.
		/// </summary>
		/// <remarks>
		///     The two widths share one ladder, so this is where a prefix that reads the wrong bytes - or
		///     drifts from the encoder - gets caught for both of them.
		/// </remarks>
		[Test]
		public void EveryPrefixDecodesAtBothWidths()
		{
			(byte[] Payload, double Value)[] cases =
			{
				(new byte[] { 0x7f }, 127),                                                 // positive fixint
				(new byte[] { 0xff }, -1),                                                  // negative fixint
				(new byte[] { 0xca, 0x00, 0x00, 0x80, 0x3f }, 1),                           // float32
				(Float64Payload(EpochMs), EpochMs),                                         // float64
				(new byte[] { 0xcc, 0xff }, 255),                                           // uint8
				(new byte[] { 0xcd, 0xff, 0xff }, 65535),                                   // uint16
				(new byte[] { 0xce, 0xff, 0xff, 0xff, 0xff }, 4294967295),                  // uint32
				(Uint64Payload((ulong)EpochMs), EpochMs),                                   // uint64
				(new byte[] { 0xd0, 0x80 }, -128),                                          // int8
				(new byte[] { 0xd1, 0x00, 0x80 }, -32768),                                  // int16
				(new byte[] { 0xd2, 0x00, 0x00, 0x00, 0x80 }, -2147483648),                 // int32
			};

			foreach ((byte[] payload, double expected) in cases)
			{
				var itWide = new Iterator { Offset = 0 };
				var itNarrow = new Iterator { Offset = 0 };

				Assert.AreEqual(expected, Decode.DecodeNumberAsDouble(payload, itWide),
					"prefix 0x{0:x2} decoded to the wrong number", payload[0]);
				Assert.AreEqual((float)expected, Decode.DecodeNumber(payload, itNarrow),
					"prefix 0x{0:x2} is not the wide value narrowed", payload[0]);
				Assert.AreEqual(payload.Length, itWide.Offset,
					"prefix 0x{0:x2} consumed the wrong number of bytes", payload[0]);
				Assert.AreEqual(itWide.Offset, itNarrow.Offset,
					"prefix 0x{0:x2} consumed a different number of bytes at each width", payload[0]);
			}
		}

		/// <summary>A schema whose collection elements can hold what its `"number"` children carry.</summary>
		public class TimestampLog : Schema.Schema
		{
			[Colyseus.Schema.Type(0, "array", typeof(ArraySchema<double>), "number")]
			public ArraySchema<double> at = null;
		}

		/// <summary>
		///     `ArraySchema&lt;double&gt;` could not decode a `"number"` at all before: `SetByIndex` casts with
		///     `(T)value`, and unboxing a float as a double throws rather than widening.
		/// </summary>
		[Test]
		public void ArrayOfDoublesReceivesTheNumbersItCanHold()
		{
			var decoder = new Colyseus.Schema.Decoder<TimestampLog>();

			var bytes = new System.Collections.Generic.List<byte>();
			bytes.AddRange(new byte[] { 0x80, 1 });     // field index 0 ("at") → refId 1
			bytes.AddRange(new byte[] { 255, 1 });      // SWITCH_TO_STRUCTURE refId 1
			bytes.Add((byte)OPERATION.ADD);
			bytes.Add(0);                               // index 0
			bytes.AddRange(Float64Payload(EpochMs));

			decoder.Decode(bytes.ToArray());

			Assert.AreEqual(1, decoder.State.at.Count);
			Assert.AreEqual(EpochMs, decoder.State.at[0]);
		}
	}
}
