using System;
using System.Globalization;
using NUnit.Framework;
using Colyseus;
using Colyseus.Schema;
using Colyseus.Schema.Utils;

namespace Colyseus.Tests
{
	/// <summary>
	///     5.0 reflection format + t.quantized decode (Phase 1).
	///
	///     Fixtures generated by schema-5.0
	///     test-external/generate-quantized-fixtures.ts (self-verified against
	///     Reflection.decode + the reference codec). Contract: colyseus-0.18
	///     PORTING/sdk-ports-quantized-reflection.md.
	/// </summary>
	[TestFixture]
	public class QuantizedTest
	{
		// rows: desc, input, q, roundtrip — behavior lock from the JS reference codec
		private const string CodecVectors = @"clamp8_0_10, 0, 0, 0
clamp8_0_10, 1, 26, 1.0196078431372548
clamp8_0_10, 10, 255, 10
clamp8_0_10, 0.0196078431372549, 1, 0.0392156862745098
clamp8_0_10, 5.5, 140, 5.490196078431373
clamp8_0_10, -1.5, 0, 0
clamp8_0_10, 1.5, 38, 1.4901960784313726
clamp8_0_10, 0.3, 8, 0.3137254901960784
clamp8_0_10, -99, 0, 0
clamp8_0_10, 99, 255, 10
clamp8_0_10, 3.141592653589793, 80, 3.1372549019607843
clamp8_0_10, 6.283185307179586, 160, 6.2745098039215685
clamp8_0_10, 7.283185307179586, 186, 7.294117647058823
clamp8_0_10, -1, 0, 0
clamp8_0_10, 360, 255, 10
clamp8_0_10, 720.5, 255, 10
clamp8_0_10, 1000000, 255, 10
clamp8_0_10, -1000000, 0, 0
clamp8_0_10, 0.123456789, 3, 0.11764705882352941
clamp8_0_10, NaN, 0, 0
clamp8_0_10, Infinity, 255, 10
clamp8_0_10, -Infinity, 0, 0
clamp16_pitch, 0, 32768, 0.00002288853284504455
clamp16_pitch, 1, 54613, 1.000022888532845
clamp16_pitch, 10, 65535, 1.5
clamp16_pitch, 0.0196078431372549, 33196, 0.01961547264820318
clamp16_pitch, 5.5, 65535, 1.5
clamp16_pitch, -1.5, 0, -1.5
clamp16_pitch, 1.5, 65535, 1.5
clamp16_pitch, 0.3, 39321, 0.2999999999999998
clamp16_pitch, -99, 0, -1.5
clamp16_pitch, 99, 65535, 1.5
clamp16_pitch, 3.141592653589793, 65535, 1.5
clamp16_pitch, 6.283185307179586, 65535, 1.5
clamp16_pitch, 7.283185307179586, 65535, 1.5
clamp16_pitch, -1, 10923, -0.999977111467155
clamp16_pitch, 360, 65535, 1.5
clamp16_pitch, 720.5, 65535, 1.5
clamp16_pitch, 1000000, 65535, 1.5
clamp16_pitch, -1000000, 0, -1.5
clamp16_pitch, 0.123456789, 35464, 0.12343785763332571
clamp16_pitch, NaN, 0, -1.5
clamp16_pitch, Infinity, 65535, 1.5
clamp16_pitch, -Infinity, 0, -1.5
clamp32_unit, 0, 0, 0
clamp32_unit, 1, 4294967295, 1
clamp32_unit, 10, 4294967295, 1
clamp32_unit, 0.0196078431372549, 84215045, 0.0196078431372549
clamp32_unit, 5.5, 4294967295, 1
clamp32_unit, -1.5, 0, 0
clamp32_unit, 1.5, 4294967295, 1
clamp32_unit, 0.3, 1288490189, 0.3000000001164153
clamp32_unit, -99, 0, 0
clamp32_unit, 99, 4294967295, 1
clamp32_unit, 3.141592653589793, 4294967295, 1
clamp32_unit, 6.283185307179586, 4294967295, 1
clamp32_unit, 7.283185307179586, 4294967295, 1
clamp32_unit, -1, 0, 0
clamp32_unit, 360, 4294967295, 1
clamp32_unit, 720.5, 4294967295, 1
clamp32_unit, 1000000, 4294967295, 1
clamp32_unit, -1000000, 0, 0
clamp32_unit, 0.123456789, 530242871, 0.12345678897655028
clamp32_unit, NaN, 0, 0
clamp32_unit, Infinity, 4294967295, 1
clamp32_unit, -Infinity, 0, 0
wrap16_angle, 0, 0, 0
wrap16_angle, 1, 10430, 0.9999637261029524
wrap16_angle, 10, 38768, 3.7168354490469087
wrap16_angle, 0.0196078431372549, 205, 0.019654128844784777
wrap16_angle, 5.5, 57367, 5.4999922411647235
wrap16_angle, -1.5, 49890, 4.783143844225915
wrap16_angle, 1.5, 15646, 1.5000414629536714
wrap16_angle, 0.3, 3129, 0.2999891178308857
wrap16_angle, -99, 15969, 1.5310087001091128
wrap16_angle, 99, 49567, 4.752176607070473
wrap16_angle, 3.141592653589793, 32768, 3.141592653589793
wrap16_angle, 6.283185307179586, 0, 0
wrap16_angle, 7.283185307179586, 10430, 0.9999637261029524
wrap16_angle, -1, 55106, 5.283221581076634
wrap16_angle, 360, 19384, 1.8584177245234543
wrap16_angle, 720.5, 43984, 4.216913185897628
wrap16_angle, 1000000, 61806, 5.925576036003746
wrap16_angle, -1000000, 3730, 0.35760927117584007
wrap16_angle, 0.123456789, 1288, 0.12348545342479411
wrap16_angle, NaN, 0, 0
wrap16_angle, Infinity, 0, 0
wrap16_angle, -Infinity, 0, 0
wrap8_degrees, 0, 0, 0
wrap8_degrees, 1, 1, 1.40625
wrap8_degrees, 10, 7, 9.84375
wrap8_degrees, 0.0196078431372549, 0, 0
wrap8_degrees, 5.5, 4, 5.625
wrap8_degrees, -1.5, 255, 358.59375
wrap8_degrees, 1.5, 1, 1.40625
wrap8_degrees, 0.3, 0, 0
wrap8_degrees, -99, 186, 261.5625
wrap8_degrees, 99, 70, 98.4375
wrap8_degrees, 3.141592653589793, 2, 2.8125
wrap8_degrees, 6.283185307179586, 4, 5.625
wrap8_degrees, 7.283185307179586, 5, 7.03125
wrap8_degrees, -1, 255, 358.59375
wrap8_degrees, 360, 0, 0
wrap8_degrees, 720.5, 0, 0
wrap8_degrees, 1000000, 199, 279.84375
wrap8_degrees, -1000000, 57, 80.15625
wrap8_degrees, 0.123456789, 0, 0
wrap8_degrees, NaN, 0, 0
wrap8_degrees, Infinity, 0, 0
wrap8_degrees, -Infinity, 0, 0
wrap32_angle, 0, 0, 0
wrap32_angle, 1, 683565276, 1.000000000619646
wrap32_angle, 10, 2540685460, 3.7168146931651997
wrap32_angle, 0.0196078431372549, 13403241, 0.019607843579674843
wrap32_angle, 5.5, 3759609016, 5.500000000482216
wrap32_angle, -1.5, 3269619383, 4.783185307713036
wrap32_angle, 1.5, 1025347913, 1.4999999994665507
wrap32_angle, 0.3, 205069583, 0.30000000047847736
wrap32_angle, -99, 1046514454, 1.5309649149710003
wrap32_angle, 99, 3248452842, 4.752220392208586
wrap32_angle, 3.141592653589793, 2147483648, 3.141592653589793
wrap32_angle, 6.283185307179586, 0, 0
wrap32_angle, 7.283185307179586, 683565276, 1.000000000619646
wrap32_angle, -1, 3611402020, 5.283185306559941
wrap32_angle, 360, 1270363336, 1.8584374914725412
wrap32_angle, 720.5, 2882509309, 4.216874981791988
wrap32_angle, 1000000, 4050548848, 5.925621140693966
wrap32_angle, -1000000, 244418448, 0.3575641664856201
wrap32_angle, 0.123456789, 84390774, 0.12345678900794896
wrap32_angle, NaN, 0, 0
wrap32_angle, Infinity, 0, 0
wrap32_angle, -Infinity, 0, 0";

		private const double TwoPi = 6.283185307179586;

		private static QuantizeDescriptor DescriptorFor(string name)
		{
			switch (name)
			{
				case "clamp8_0_10": return Quantize.Resolve(0, 10, 8, false);
				case "clamp16_pitch": return Quantize.Resolve(-1.5, 1.5, 16, false);
				case "clamp32_unit": return Quantize.Resolve(0, 1, 32, false);
				case "wrap16_angle": return Quantize.Resolve(0, TwoPi, 16, true);
				case "wrap8_degrees": return Quantize.Resolve(0, 360, 8, true);
				case "wrap32_angle": return Quantize.Resolve(0, TwoPi, 32, true);
				default: throw new Exception("unknown descriptor: " + name);
			}
		}

		private static double ParseNumber(string s)
		{
			switch (s)
			{
				case "NaN": return double.NaN;
				case "Infinity": return double.PositiveInfinity;
				case "-Infinity": return double.NegativeInfinity;
				default: return double.Parse(s, CultureInfo.InvariantCulture);
			}
		}

		[Test]
		public void CodecVectorsTest()
		{
			var rows = 0;
			foreach (var line in CodecVectors.Split('\n'))
			{
				var cols = line.Trim().Split(new[] { ", " }, StringSplitOptions.None);
				var desc = DescriptorFor(cols[0]);
				var input = ParseNumber(cols[1]);
				var expectedQ = uint.Parse(cols[2]);
				var expectedRoundtrip = ParseNumber(cols[3]);

				var q = Quantize.QuantizeValue(desc, input);
				Assert.AreEqual(expectedQ, q, $"{cols[0]} input={cols[1]}");
				// shortest-roundtrip decimal parses back to the identical float64
				Assert.AreEqual(BitConverter.DoubleToInt64Bits(expectedRoundtrip),
					BitConverter.DoubleToInt64Bits(Quantize.Dequantize(desc, q)),
					$"{cols[0]} input={cols[1]} roundtrip");
				rows++;
			}
			Assert.AreEqual(132, rows);
		}

		[Test]
		public void ReflectionAndQuantizedStateTest()
		{
			// 5.0 reflection handshake: quantized descriptors, childPrimitive
			// collection slots (no colon packing), schema refs — into
			// DynamicSchema definitions
			var serializer = new SchemaSerializer<DynamicSchema>();
			serializer.Handshake(new byte[] { 128, 1, 255, 1, 128, 0, 2, 128, 1, 15, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 6, 128, 2, 8, 128, 3, 10, 128, 4, 11, 128, 5, 12, 128, 6, 13, 128, 7, 14, 255, 4, 128, 163, 121, 97, 119, 129, 169, 113, 117, 97, 110, 116, 105, 122, 101, 100, 132, 5, 255, 5, 128, 0, 0, 0, 0, 0, 0, 0, 0, 129, 24, 45, 68, 84, 251, 33, 25, 64, 130, 16, 131, 1, 255, 6, 128, 165, 112, 105, 116, 99, 104, 129, 169, 113, 117, 97, 110, 116, 105, 122, 101, 100, 132, 7, 255, 7, 128, 0, 0, 0, 0, 0, 0, 248, 191, 129, 0, 0, 0, 0, 0, 0, 248, 63, 130, 8, 131, 0, 255, 8, 128, 167, 112, 114, 101, 99, 105, 115, 101, 129, 169, 113, 117, 97, 110, 116, 105, 122, 101, 100, 132, 9, 255, 9, 128, 0, 0, 0, 0, 0, 0, 0, 0, 129, 0, 0, 0, 0, 0, 0, 240, 63, 130, 32, 131, 0, 255, 10, 128, 164, 110, 117, 109, 115, 129, 165, 97, 114, 114, 97, 121, 130, 255, 131, 166, 110, 117, 109, 98, 101, 114, 255, 11, 128, 164, 116, 97, 103, 115, 129, 163, 109, 97, 112, 130, 255, 131, 166, 115, 116, 114, 105, 110, 103, 255, 12, 128, 165, 99, 104, 105, 108, 100, 129, 163, 114, 101, 102, 130, 1, 255, 13, 128, 165, 105, 116, 101, 109, 115, 129, 165, 97, 114, 114, 97, 121, 130, 1, 255, 14, 128, 165, 108, 97, 98, 101, 108, 129, 166, 115, 116, 114, 105, 110, 103, 255, 15, 128, 1, 130, 16, 255, 16, 128, 0, 17, 255, 17, 128, 161, 118, 129, 166, 110, 117, 109, 98, 101, 114 }, 0);

			// full state
			serializer.SetState(new byte[] { 128, 238, 50, 129, 187, 130, 55, 221, 154, 31, 131, 1, 132, 2, 133, 5, 134, 4, 135, 161, 113, 255, 1, 128, 0, 1, 128, 1, 202, 0, 0, 32, 64, 128, 2, 3, 255, 2, 128, 0, 161, 97, 161, 120, 255, 5, 128, 7, 255, 4, 128, 0, 6, 128, 1, 7, 255, 6, 128, 1, 255, 7, 128, 2 });

			var state = serializer.GetState();

			Assert.AreEqual(1.2500025945283118, state.Get<double>("yaw"));
			Assert.AreEqual(0.6999999999999997, state.Get<double>("pitch"));
			Assert.AreEqual(0.12345678897655028, state.Get<double>("precise"));
			Assert.AreEqual("q", state.Get<string>("label"));

			// childPrimitive: nums is array-of-number, tags map-of-string
			var nums = state.Get<ArraySchema<object>>("nums");
			Assert.AreEqual(3, nums.Count);
			Assert.AreEqual(2.5f, nums[1]);

			var tags = state.Get<MapSchema<object>>("tags");
			Assert.AreEqual("x", tags["a"]);

			var child = state.Get<DynamicSchema>("child");
			Assert.AreEqual(7f, child.Get<float>("v"));

			var items = state.Get<ArraySchema<DynamicSchema>>("items");
			Assert.AreEqual(2, items.Count);
			Assert.AreEqual(1f, items[0].Get<float>("v"));
			Assert.AreEqual(2f, items[1].Get<float>("v"));

			// patch: yaw changes, pitch clamps to min, nums grows
			serializer.Patch(new byte[] { 128, 250, 162, 129, 0, 255, 1, 128, 3, 4 });

			Assert.AreEqual(4.000046652010295, state.Get<double>("yaw"));
			Assert.AreEqual(-1.5, state.Get<double>("pitch"));
			Assert.AreEqual(4, state.Get<ArraySchema<object>>("nums").Count);
		}
	}
}
