using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using NUnit.Framework;
using Colyseus;

namespace Colyseus.Tests
{
	/// <summary>
	///     0.18 wire-compat (Phase 0) — room-level protocol frames.
	///
	///     Fixtures below generated by colyseus-0.18
	///     PORTING/generate-phase0-fixtures.cts (self-verified against the JS
	///     packages/sdk Room). See PORTING/sdk-coverage-plan-0.18.md.
	/// </summary>
	[TestFixture]
	public class RoomProtocolTest
	{
		private class StubConnection : Connection
		{
			public readonly List<byte[]> Sent = new List<byte[]>();

			public StubConnection() : base("ws://localhost", null)
			{
				IsOpen = true;
				Transmit = data =>
				{
					Sent.Add((byte[])data.Clone());
					return Task.CompletedTask;
				};
			}
		}

		private class TestRoom : Room<SchemaTest.Phase0.P0State>
		{
			public TestRoom() : base("phase0")
			{
				RoomId = "phase0";
			}

			public void Feed(byte[] frame)
			{
				ParseMessage(frame);
			}
		}

		private static (TestRoom room, StubConnection stub) MakeRoom()
		{
			var room = new TestRoom();
			var stub = new StubConnection();
			room.SetConnection(stub);
			return (room, stub);
		}

		[Test]
		public void JoinRoomFullHandshakeTest()
		{
			var (room, stub) = MakeRoom();

			var joins = 0;
			room.OnJoin += () => joins++;

			// JOIN_ROOM with length-prefixed state reflection + INPUT_REFLECTION
			// and INPUT_OPTIONS tagged sections (room uses defineInput())
			room.Feed(new byte[] { 10, 6, 116, 111, 107, 49, 50, 51, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114, 1, 47, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 161, 120, 129, 166, 110, 117, 109, 98, 101, 114, 255, 5, 128, 161, 121, 129, 166, 110, 117, 109, 98, 101, 114, 2, 4, 14, 20, 50, 2 });

			Assert.AreEqual(1, joins);
			Assert.AreEqual("tok123", room.ReconnectionToken.Token);

			// acknowledged with a single JOIN_ROOM byte
			Assert.AreEqual(1, stub.Sent.Count);
			CollectionAssert.AreEqual(new byte[] { 10 }, stub.Sent[0]);

			// full state decodes through the real schema serializer
			room.Feed(new byte[] { 14, 128, 165, 104, 101, 108, 108, 111, 129, 42 });
			Assert.AreEqual("hello", room.State.msg);
			Assert.AreEqual(42, room.State.n);

			// TIMED-modified patch (143 = 15 | 0x80): the 8-byte
			// [uint32 sNow][uint32 inputSeq] prefix must be consumed
			room.Feed(new byte[] { 143, 64, 226, 1, 0, 7, 0, 0, 0, 129, 43 });
			Assert.AreEqual(43, room.State.n);
		}

		[Test]
		public void JoinRoomReconnectTest()
		{
			var (room, _) = MakeRoom();

			var joins = 0;
			var reconnects = 0;
			room.OnJoin += () => joins++;
			room.OnReconnect += () => reconnects++;

			// plain room: state reflection only, no trailing sections
			room.Feed(new byte[] { 10, 4, 116, 111, 107, 65, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114 });
			Assert.AreEqual(1, joins);
			Assert.AreEqual(0, reconnects);

			// reconnect JOIN: zero-length state reflection (serializer has state)
			room.Feed(new byte[] { 10, 4, 116, 111, 107, 66, 6, 115, 99, 104, 101, 109, 97, 0 });
			Assert.AreEqual(1, joins);
			Assert.AreEqual(1, reconnects);
			Assert.AreEqual("tokB", room.ReconnectionToken.Token);
		}

		[Test]
		public void RequestFrameEncodingTest()
		{
			var (room, stub) = MakeRoom();

			_ = room.Request<float>("move", 7);

			// [21][requestId 0]['move' fixstr][msgpack 7]
			Assert.AreEqual(1, stub.Sent.Count);
			CollectionAssert.AreEqual(new byte[] { 21, 0, 164, 109, 111, 118, 101, 7 }, stub.Sent[0]);
		}

		[Test]
		public async Task RequestResponseOutcomesTest()
		{
			var (room, _) = MakeRoom();

			// ids mint from 0 in order
			var okWithPayload = room.Request<float>("a");
			var okEmpty = room.Request<object>("b");
			var rejected = room.Request<object>("c");
			var faulted = room.Request<object>("d");

			room.Feed(new byte[] { 22, 0, 0, 42 });                      // OK, payload 42
			room.Feed(new byte[] { 22, 1, 0 });                          // OK, no payload
			room.Feed(new byte[] { 22, 2, 1, 164, 110, 111, 112, 101 }); // REJECTED, "nope"
			room.Feed(new byte[] { 22, 3, 2, 222, 0, 2, 164, 110, 97, 109, 101, 165, 69, 114, 114, 111, 114, 167, 109, 101, 115, 115, 97, 103, 101, 164, 98, 111, 111, 109 }); // ERROR, {name,message}
			room.Feed(new byte[] { 22, 205, 231, 3, 0, 1 });             // unknown id 999 — ignored

			Assert.AreEqual(42, await okWithPayload);
			Assert.IsNull(await okEmpty);

			var rejection = Assert.ThrowsAsync<RequestError>(async () => await rejected);
			Assert.AreEqual("nope", rejection.Payload);
			Assert.IsFalse(rejection.Faulted);

			var fault = Assert.ThrowsAsync<RequestError>(async () => await faulted);
			Assert.IsTrue(fault.Faulted);
			Assert.AreEqual("boom", fault.Message);
		}

		[Test]
		public void RequestWhileClosedTest()
		{
			var (room, stub) = MakeRoom();
			stub.IsOpen = false;

			Assert.ThrowsAsync<Exception>(async () => await room.Request<object>("a"));
		}
	}
}
