using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using NUnit.Framework;
using Colyseus;

namespace Colyseus.Tests
{
	/// <summary>
	///     0.18 wire-compat (Phase 0) — room-level protocol frames.
	///
	///     Fixtures below generated by colyseus-0.18
	///     PORTING/generate-phase0-fixtures.cts (self-verified against the JS
	///     packages/sdk Room). See PORTING/sdk-coverage-plan-0.18.md.
	/// </summary>
	[TestFixture]
	public class RoomProtocolTest
	{
		private class StubConnection : Connection
		{
			public readonly List<byte[]> Sent = new List<byte[]>();

			public StubConnection() : base("ws://localhost", null)
			{
				IsOpen = true;
				Transmit = data =>
				{
					Sent.Add((byte[])data.Clone());
					return Task.CompletedTask;
				};
			}
		}

		private class TestRoom : Room<SchemaTest.Phase0.P0State>
		{
			public TestRoom() : base("phase0")
			{
				RoomId = "phase0";
			}

			public void Feed(byte[] frame)
			{
				ParseMessage(frame);
			}

			public long ClockOffsetMs;
			protected override long NowMs() => base.NowMs() + ClockOffsetMs;
		}

		private static (TestRoom room, StubConnection stub) MakeRoom()
		{
			var room = new TestRoom();
			var stub = new StubConnection();
			room.SetConnection(stub);
			return (room, stub);
		}

		[Test]
		public void JoinRoomFullHandshakeTest()
		{
			var (room, stub) = MakeRoom();

			var joins = 0;
			room.OnJoin += () => joins++;

			// JOIN_ROOM with length-prefixed state reflection + INPUT_REFLECTION
			// and INPUT_OPTIONS tagged sections (room uses defineInput())
			room.Feed(new byte[] { 10, 6, 116, 111, 107, 49, 50, 51, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114, 1, 47, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 161, 120, 129, 166, 110, 117, 109, 98, 101, 114, 255, 5, 128, 161, 121, 129, 166, 110, 117, 109, 98, 101, 114, 2, 4, 14, 20, 50, 2 });

			Assert.AreEqual(1, joins);
			Assert.AreEqual("tok123", room.ReconnectionToken.Token);

			// acknowledged with a single JOIN_ROOM byte
			Assert.AreEqual(1, stub.Sent.Count);
			CollectionAssert.AreEqual(new byte[] { 10 }, stub.Sent[0]);

			// full state decodes through the real schema serializer
			room.Feed(new byte[] { 14, 128, 165, 104, 101, 108, 108, 111, 129, 42 });
			Assert.AreEqual("hello", room.State.msg);
			Assert.AreEqual(42, room.State.n);

			// TIMED-modified patch (143 = 15 | 0x80): the 8-byte
			// [uint32 sNow][uint32 inputSeq] prefix must be consumed
			room.Feed(new byte[] { 143, 64, 226, 1, 0, 7, 0, 0, 0, 129, 43 });
			Assert.AreEqual(43, room.State.n);
		}

		[Test]
		public void JoinRoomReconnectTest()
		{
			var (room, _) = MakeRoom();

			var joins = 0;
			var reconnects = 0;
			room.OnJoin += () => joins++;
			room.OnReconnect += () => reconnects++;

			// plain room: state reflection only, no trailing sections
			room.Feed(new byte[] { 10, 4, 116, 111, 107, 65, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114 });
			Assert.AreEqual(1, joins);
			Assert.AreEqual(0, reconnects);

			// reconnect JOIN: zero-length state reflection (serializer has state)
			room.Feed(new byte[] { 10, 4, 116, 111, 107, 66, 6, 115, 99, 104, 101, 109, 97, 0 });
			Assert.AreEqual(1, joins);
			Assert.AreEqual(1, reconnects);
			Assert.AreEqual("tokB", room.ReconnectionToken.Token);
		}

		[Test]
		public void RequestFrameEncodingTest()
		{
			var (room, stub) = MakeRoom();

			_ = room.Request<float>("move", 7);

			// [21][requestId 0]['move' fixstr][msgpack 7]
			Assert.AreEqual(1, stub.Sent.Count);
			CollectionAssert.AreEqual(new byte[] { 21, 0, 164, 109, 111, 118, 101, 7 }, stub.Sent[0]);
		}

		[Test]
		public async Task RequestResponseOutcomesTest()
		{
			var (room, _) = MakeRoom();

			// ids mint from 0 in order
			var okWithPayload = room.Request<float>("a");
			var okEmpty = room.Request<object>("b");
			var rejected = room.Request<object>("c");
			var faulted = room.Request<object>("d");

			room.Feed(new byte[] { 22, 0, 0, 42 });                      // OK, payload 42
			room.Feed(new byte[] { 22, 1, 0 });                          // OK, no payload
			room.Feed(new byte[] { 22, 2, 1, 164, 110, 111, 112, 101 }); // REJECTED, "nope"
			room.Feed(new byte[] { 22, 3, 2, 222, 0, 2, 164, 110, 97, 109, 101, 165, 69, 114, 114, 111, 114, 167, 109, 101, 115, 115, 97, 103, 101, 164, 98, 111, 111, 109 }); // ERROR, {name,message}
			room.Feed(new byte[] { 22, 205, 231, 3, 0, 1 });             // unknown id 999 — ignored

			Assert.AreEqual(42, await okWithPayload);
			Assert.IsNull(await okEmpty);

			var rejection = Assert.ThrowsAsync<RequestError>(async () => await rejected);
			Assert.AreEqual("nope", rejection.Payload);
			Assert.IsFalse(rejection.Faulted);

			var fault = Assert.ThrowsAsync<RequestError>(async () => await faulted);
			Assert.IsTrue(fault.Faulted);
			Assert.AreEqual("boom", fault.Message);
		}

		[Test]
		public void RequestWhileClosedTest()
		{
			var (room, stub) = MakeRoom();
			stub.IsOpen = false;

			Assert.ThrowsAsync<Exception>(async () => await room.Request<object>("a"));
		}

		[Test]
		public void NumericTypeEncodingTest()
		{
			var (room, stub) = MakeRoom();

			// the type rides as a schema "number": positive fixint below 0x80,
			// uint8-prefixed above — a raw 0x80+ byte would parse as a
			// fixmap/fixstr prefix on the server
			_ = room.Request<object>(5, 7);
			_ = room.Request<object>(200);
			_ = room.Send(5);
			_ = room.Send(200, 1);
			_ = room.SendBytes(200, new byte[] { 9 });

			CollectionAssert.AreEqual(new byte[] { 21, 0, 5, 7 }, stub.Sent[0]);
			CollectionAssert.AreEqual(new byte[] { 21, 1, 0xcc, 200 }, stub.Sent[1]);
			CollectionAssert.AreEqual(new byte[] { 13, 5 }, stub.Sent[2]);
			CollectionAssert.AreEqual(new byte[] { 13, 0xcc, 200, 1 }, stub.Sent[3]);
			CollectionAssert.AreEqual(new byte[] { 17, 0xcc, 200, 9 }, stub.Sent[4]);
		}

		[Test]
		public void RequestIdEncodingTest()
		{
			var (room, stub) = MakeRoom();

			var requests = new List<Task<object>>();
			for (var i = 0; i < 300; i++) { requests.Add(room.Request<object>("a")); }

			// id 128 → uint8 prefix; id 256 → uint16 prefix (little-endian)
			CollectionAssert.AreEqual(new byte[] { 21, 0xcc, 128, 161, 97 }, stub.Sent[128]);
			CollectionAssert.AreEqual(new byte[] { 21, 0xcd, 0, 1, 161, 97 }, stub.Sent[256]);

			// and the reply correlates through the same codec
			room.Feed(new byte[] { 22, 0xcd, 0, 1, 0, 42 });
			Assert.AreEqual(42, requests[256].Result);
			Assert.IsFalse(requests[255].IsCompleted);
		}

		[Test]
		public async Task RequestErrorShapeTest()
		{
			var (room, _) = MakeRoom();

			var rejected = room.Request<object>("a");
			var noHandler = room.Request<object>("b");
			var coded = room.Request<object>("c");

			room.Feed(new byte[] { 22, 0, 1, 164, 110, 111, 112, 101 }); // REJECTED "nope"
			// ERROR {name:"no_handler", message:"missing"}
			room.Feed(new byte[] { 22, 1, 2, 0x82, 0xa4, 110, 97, 109, 101, 0xaa, 110, 111, 95, 104, 97, 110, 100, 108, 101, 114, 0xa7, 109, 101, 115, 115, 97, 103, 101, 0xa7, 109, 105, 115, 115, 105, 110, 103 });
			// ERROR {name:"Error", message:"boom", code:7}
			room.Feed(new byte[] { 22, 2, 2, 0x83, 0xa4, 110, 97, 109, 101, 0xa5, 69, 114, 114, 111, 114, 0xa7, 109, 101, 115, 115, 97, 103, 101, 0xa4, 98, 111, 111, 109, 0xa4, 99, 111, 100, 101, 7 });

			var rejection = Assert.ThrowsAsync<RequestError>(async () => await rejected);
			Assert.AreEqual("rejected", rejection.Name);
			Assert.AreEqual("request rejected", rejection.Message);
			Assert.AreEqual("nope", rejection.Payload);
			Assert.IsNull(rejection.Code);

			var missing = Assert.ThrowsAsync<RequestError>(async () => await noHandler);
			Assert.AreEqual("no_handler", missing.Name);
			Assert.AreEqual("missing", missing.Message);
			Assert.IsTrue(missing.Faulted);

			var fault = Assert.ThrowsAsync<RequestError>(async () => await coded);
			Assert.AreEqual("Error", fault.Name);
			Assert.AreEqual("boom", fault.Message);
			Assert.AreEqual(7, Convert.ToInt32(fault.Code));
			await Task.CompletedTask;
		}

		[Test]
		public void SendWithCallbackTest()
		{
			var (room, stub) = MakeRoom();

			object okResponse = null; Exception okError = null;
			object failResponse = "untouched"; Exception failError = null;

			room.Send<object>("a", 1, (res, err) => { okResponse = res; okError = err; });
			room.Send<object>(9, null, (res, err) => { failResponse = res; failError = err; });

			// callback form is a plain ROOM_REQUEST on the wire
			CollectionAssert.AreEqual(new byte[] { 21, 0, 161, 97, 1 }, stub.Sent[0]);
			CollectionAssert.AreEqual(new byte[] { 21, 1, 9 }, stub.Sent[1]);

			room.Feed(new byte[] { 22, 0, 0, 42 });
			room.Feed(new byte[] { 22, 1, 1, 164, 110, 111, 112, 101 });

			Assert.AreEqual(42, okResponse);
			Assert.IsNull(okError);

			Assert.IsNull(failResponse);
			Assert.IsInstanceOf<RequestError>(failError);
			Assert.AreEqual("nope", ((RequestError)failError).Payload);
		}

		[Test]
		public async Task RequestTimeoutTest()
		{
			var (room, _) = MakeRoom();

			var request = room.Request<object>("slow", null, 20);
			var timeout = Assert.ThrowsAsync<TimeoutException>(async () => await request);
			StringAssert.Contains("timed out after 20ms", timeout.Message);

			// the late reply finds no pending entry and is ignored
			room.Feed(new byte[] { 22, 0, 0, 42 });
			await Task.CompletedTask;
		}

		[Test]
		public void RequestSweepOnInboundFrameTest()
		{
			var (room, _) = MakeRoom();

			// the 10s timer won't fire during the test; only the sweep can
			var request = room.Request<object>("slow", null, 10_000);
			room.ClockOffsetMs = 10_001;

			// no timer has to fire: the next inbound frame (a PONG here) expires
			// it inline — the WebGL path
			room.Feed(new byte[] { 18 });

			Assert.IsTrue(request.IsFaulted);
			Assert.IsInstanceOf<TimeoutException>(request.Exception.InnerException);
		}

		[Test]
		public void RequestRejectedOnCloseTest()
		{
			var (room, stub) = MakeRoom();

			var request = room.Request<object>("a");
			stub.Dispatch(ConnectionEvent.Closed((int) CloseCode.CONSENTED));

			Assert.IsTrue(request.IsFaulted);
			StringAssert.Contains("connection closed", request.Exception.InnerException.Message);
		}
	}
}
