//
// GENERATED by generate-collection-fixtures.ts (next to this file) against the
// real @colyseus/schema encoder/decoder — do not edit by hand; re-run it.
//

namespace Colyseus.Tests.Fixtures
{
	internal static class CollectionFixtures
	{
		/// <summary>Full state for an EMPTY view: the view-filtered "heroes" map is absent.</summary>
		public static readonly byte[] ViewFull = new byte[] { 129, 1, 0, 130, 2, 255, 2, 128, 0, 162, 111, 49, 6, 255, 6, 128, 45, 129, 30 };

		/// <summary>P0 heroes arrives with "a" · P1 "b" · P2 view drops "a" · P3 tick=2, open.o1.hp=31 · P4 "a" back · P5 "b" deleted.</summary>
		public static readonly byte[][] ViewPatches =
		{
			new byte[] { 255, 0, 128, 1, 255, 1, 128, 0, 161, 97, 3, 255, 3, 128, 15, 129, 10 },
			new byte[] { 255, 0, 128, 1, 255, 1, 128, 1, 161, 98, 9, 255, 1, 128, 1, 161, 98, 9, 255, 9, 128, 30, 129, 20 },
			new byte[] { 255, 1, 64, 0 },
			new byte[] { 129, 2, 0, 255, 6, 129, 31 },
			new byte[] { 255, 0, 128, 1, 255, 1, 128, 0, 161, 97, 3, 255, 3, 128, 15, 129, 10 },
			new byte[] { 255, 1, 64, 1 },
		};

		/// <summary>The JS Callbacks event log over the same registrations.</summary>
		public static readonly string[] ViewLog =
		{
			"L:0:null",
			"--full",
			"tick:1",
			"open.add:o1:30",
			"--P0",
			"L:1:0",
			"A.add:a:10",
			"B.add:a:10",
			"C.add:a:10",
			"--P1",
			"L:2:2",
			"C.add:b:20",
			"A.add:b:20",
			"B.add:b:20",
			"--P2",
			"C.remove:a:10",
			"A.remove:a:10",
			"B.remove:a:10",
			"--P3",
			"tick:2",
			"--P4",
			"L:2:2",
			"C.add:a:10",
			"A.add:a:10",
			"B.add:a:10",
			"--P5",
			"C.remove:b:20",
			"A.remove:b:20",
			"B.remove:b:20",
		};

		/// <summary>heroes' key order after each patch — JS Map iteration order.</summary>
		public static readonly string[] ViewKeyOrder = { "a", "a,b", "b", "b", "b,a", "a" };

		/// <summary>JS swaps the default instance for a fresh decoded one when the collection first arrives.</summary>
		public const bool ViewReplacedOnArrival = true;

		/// <summary>f=0.1, nums=[0.1, 1/3], tags={k:0.7} — all float32 on the wire.</summary>
		public static readonly byte[] Wide = new byte[] { 128, 205, 204, 204, 61, 129, 1, 130, 2, 255, 1, 128, 0, 205, 204, 204, 61, 128, 1, 171, 170, 170, 62, 255, 2, 128, 0, 161, 107, 51, 51, 51, 63 };

		/// <summary>What the JS decoder yields (Math.fround of each input).</summary>
		public static readonly double[] WideValues = { 0.10000000149011612, 0.10000000149011612, 0.3333333432674408, 0.699999988079071 };
	}
}
