//
// GENERATED by generate-resend-fixtures.ts (next to this file) against the
// real @colyseus/schema encoder/decoder — do not edit by hand; re-run it.
//

namespace Colyseus.Tests.Fixtures
{
	internal static class ResendFixtures
	{
		/// <summary>Full state the first client (A) got on its ack.</summary>
		public static readonly byte[] FullA = new byte[] { 128, 168, 65, 32, 106, 111, 105, 110, 101, 100, 129, 1, 130, 0, 0, 0, 63, 131, 1, 132, 2, 133, 3, 134, 4, 255, 1, 128, 0, 161, 65, 255, 2, 128, 0, 1, 255, 3, 128, 0, 5, 255, 5, 128, 161, 65, 255, 4, 128, 0, 161, 65, 161, 65 };

		/// <summary>Full state the joiner (B) got on its ack, before the patch tick.</summary>
		public static readonly byte[] FullB = new byte[] { 128, 168, 66, 32, 106, 111, 105, 110, 101, 100, 129, 2, 130, 0, 0, 128, 62, 131, 1, 132, 2, 133, 3, 134, 4, 255, 1, 128, 0, 161, 65, 128, 1, 161, 66, 255, 2, 128, 0, 1, 128, 1, 2, 255, 3, 128, 0, 5, 128, 1, 6, 255, 5, 128, 161, 65, 255, 6, 128, 161, 66, 255, 4, 128, 0, 161, 65, 161, 65, 128, 1, 161, 66, 161, 66 };

		/// <summary>The next patch: re-sends both joins.</summary>
		public static readonly byte[] Tick1 = new byte[] { 128, 168, 66, 32, 106, 111, 105, 110, 101, 100, 129, 2, 130, 0, 0, 128, 62, 131, 1, 132, 2, 133, 3, 134, 4, 255, 1, 128, 0, 161, 65, 128, 1, 161, 66, 255, 2, 128, 0, 1, 128, 1, 2, 255, 3, 128, 0, 5, 128, 1, 6, 255, 4, 128, 0, 161, 65, 161, 65, 128, 1, 161, 66, 161, 66, 255, 5, 128, 161, 65, 255, 6, 128, 161, 66 };

		/// <summary>order + "C", names.C, label = "later", score = 3.</summary>
		public static readonly byte[] Tick2 = new byte[] { 255, 1, 128, 2, 161, 67, 255, 4, 128, 2, 161, 67, 161, 67, 255, 0, 128, 165, 108, 97, 116, 101, 114, 129, 3 };

		/// <summary>The JS Callbacks log for client A over full / tick1 / tick2.</summary>
		public static readonly string[] LogA =
		{
			"--full",
			"label=A joined",
			"score=1",
			"ratio=0.5",
			"order+0=A",
			"nums+0=1",
			"units+0=A",
			"names+A=A",
			"--tick1",
			"label=B joined",
			"score=2",
			"ratio=0.25",
			"order+1=B",
			"nums+1=2",
			"units+1=B",
			"names+B=B",
			"--tick2",
			"order+2=C",
			"names+C=C",
			"label=later",
			"score=3",
		};

		/// <summary>The JS Callbacks log for client B over full / tick1 / tick2.</summary>
		public static readonly string[] LogB =
		{
			"--full",
			"label=B joined",
			"score=2",
			"ratio=0.25",
			"order+0=A",
			"order+1=B",
			"nums+0=1",
			"nums+1=2",
			"units+0=A",
			"units+1=B",
			"names+A=A",
			"names+B=B",
			"--tick1",
			"--tick2",
			"order+2=C",
			"names+C=C",
			"label=later",
			"score=3",
		};

		public const string StateAfterTicks = "label=later score=3 ratio=0.25 order=[A,B,C] nums=[1,2] units=[A,B] names=[A:A,B:B,C:C]";

		/// <summary>Join snapshot, then (offline) names.k2 deleted, score = 5, order popped.</summary>
		public static readonly byte[] ResyncJoin = new byte[] { 128, 164, 108, 105, 118, 101, 129, 1, 130, 0, 0, 0, 63, 131, 1, 132, 2, 133, 3, 134, 4, 255, 1, 128, 0, 161, 120, 128, 1, 161, 121, 255, 2, 128, 0, 1, 128, 1, 2, 255, 3, 128, 0, 5, 255, 5, 128, 161, 117, 255, 4, 128, 0, 162, 107, 49, 161, 97, 128, 1, 162, 107, 50, 161, 98 };

		public static readonly byte[] ResyncSnapshot = new byte[] { 128, 164, 108, 105, 118, 101, 129, 5, 130, 0, 0, 0, 63, 131, 1, 132, 2, 133, 3, 134, 4, 255, 1, 128, 0, 161, 120, 255, 2, 128, 0, 1, 128, 1, 2, 255, 3, 128, 0, 5, 255, 5, 128, 161, 117, 255, 4, 128, 0, 162, 107, 49, 161, 97 };

		/// <summary>The JS Callbacks log for decodeResync over the join state.</summary>
		public static readonly string[] ResyncLog =
		{
			"score=5",
			"order-1=y",
			"names-k2=b",
		};

		public const string ResyncState = "label=live score=5 ratio=0.5 order=[x] nums=[1,2] units=[u] names=[k1:a]";
	}
}
