using System;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Security;
using GameDevWare.Serialization.Serializers;

#pragma warning disable 1591

// ReSharper disable once CheckNamespace
namespace GameDevWare.Serialization
{
	[Serializable]
	public class JsonSerializationException : SerializationException
	{
		public enum ErrorCode
		{
			SerializationException = 1,
			EmptyMemberName,
			DiscriminatorNotFirstMemberOfObject,
			CantCreateInstanceOfType,
			SerializationGraphIsTooBig,
			SerializationGraphIsTooDeep,
			TypeIsNotValid,
			SerializingUnknownType,
			SerializingSpecialSystemType,
			UnexpectedEndOfStream,
			UnexpectedMemberName,
			UnexpectedToken,
			UnknownEscapeSequence,
			UnknownDiscriminatorValue,
			SerializationFramesCorruption,
			StreamIsNotReadable,
			StreamIsNotWriteable,
			UnterminatedStringLiteral,
			UnknownNotation,
			MemberNameIsNotSpecified,
			TypeRequiresCustomSerializer,
			CircularReferenceDetected,
			FailedToReadDictionaryKey,
			FailedToReadDictionaryValue,
			UnsupportedMemberType,
			CantSerializeDelegateType,
			MemberIsWriteOnly,
			MemberIsReadOnly,
			FailedToResolveMemberType,
			FailedToReadMemberValue,
			FailedToSetMemberValue,
			FailedToParseDateTime
		}

		public ErrorCode Code { get; set; }
		public int LineNumber { get; set; }
		public int ColumnNumber { get; set; }
		public ulong CharactersWritten { get; set; }

		internal JsonSerializationException(string message, ErrorCode errorCode, IJsonReader reader = null)
			: base(message)
		{
			this.Code = errorCode;
			if (reader != null)
				this.Update(reader);
		}
		internal JsonSerializationException(string message, ErrorCode errorCode, IJsonReader reader, Exception innerException)
			: base(message, innerException)
		{
			this.Code = errorCode;
			if (reader != null)
				this.Update(reader);
		}
		internal JsonSerializationException(string message, Exception innerException)
			: base(message, innerException)
		{
			this.Code = ErrorCode.SerializationException;
		}

		protected JsonSerializationException(SerializationInfo info, StreamingContext context)
			: base(info, context)
		{
			this.Code = (ErrorCode)info.GetInt32("Code");
			this.LineNumber = info.GetInt32("LineNumber");
			this.ColumnNumber = info.GetInt32("ColumnNumber");
			this.CharactersWritten = info.GetUInt64("CharactersWritten");
		}

		private void Update(IJsonReader reader)
		{
			this.LineNumber = reader.Value.LineNumber;
			this.ColumnNumber = reader.Value.ColumnNumber;
			//this.Path = reader.Value.Path;
		}

		[SecurityCritical]
		public override void GetObjectData(SerializationInfo info, StreamingContext context)
		{
			info.AddValue("Code", (int)this.Code);
			info.AddValue("LineNumber", this.LineNumber);
			info.AddValue("ColumnNumber", this.ColumnNumber);
			info.AddValue("CharactersWritten", this.CharactersWritten);

			base.GetObjectData(info, context);
		}

		public static Exception MemberNameIsEmpty(IJsonReader reader)
		{
			return new JsonSerializationException
			(
				string.Format("An empty member name was deserialized at path '{0}'. This can occur when the input JSON contains an empty key or if there is an error in a custom serializer. Ensure all object keys are non-empty strings.", reader.Context.GetPath()),
				ErrorCode.EmptyMemberName,
				reader
			);
		}
		public static Exception MemberNameIsNotSet()
		{
			return new JsonSerializationException
			(
				"A member name is not set before writing a value to an object. This usually indicates that a custom 'TypeSerializer' implementation is missing a 'WriteMember()' call before writing a property value.",
				ErrorCode.MemberNameIsNotSpecified
			);
		}
		public static Exception DiscriminatorIsNotFirstMember(IJsonReader reader)
		{
			return new JsonSerializationException
			(
				string.Format("The type discriminator member '{0}' must be the first member of the object at path '{1}'. This often happens when the JSON was generated by a tool that does not preserve property order or when the discriminator was added manually. Ensure the '$type' or '_type' property appears first.", ObjectSerializer.TYPE_MEMBER_NAME, reader.Context.GetPath()),
				ErrorCode.DiscriminatorNotFirstMemberOfObject,
				reader
			);
		}
		public static Exception CantCreateInstanceOfType(Type type)
		{
			var constructors = type.GetConstructors(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
			var allConstructors = "<empty>";
			if (constructors.Length > 0)
			{
				allConstructors = string.Join("\r\n", constructors.Select(ctr => ctr.ToString()).ToArray());
			}

			return new JsonSerializationException
			(
				string.Format("Unable to deserialize instance of '{0}' because ", type.FullName) +
					(type.GetTypeInfo().IsAbstract ? "it is an abstract type." : "no parameter-less constructor is defined for the type. All constructors: \r\n\t" + allConstructors),
				ErrorCode.CantCreateInstanceOfType
			);
		}
		public static Exception SerializationGraphIsTooBig(IJsonReader reader, ulong maxObjects)
		{
			return new JsonSerializationException
			(
				string.Format("The serialization graph exceeds the maximum allowed number of objects ({0}) at path '{1}'. This might be caused by extremely large data structures or an infinite loop in object references. Consider increasing 'SerializationContext.MaxObjects' if this is intentional.", maxObjects, reader.Context.GetPath()),
				ErrorCode.SerializationGraphIsTooBig
			);
		}
		public static Exception SerializationGraphIsTooDeep(IJsonReader reader, ulong maxDepth)
		{
			return new JsonSerializationException
			(
					string.Format("The serialization graph exceeds the maximum allowed depth ({0}) at path '{1}'. This often points to circular object references or very deep nesting. Consider increasing 'SerializationContext.MaxDepth' if this is intentional, or check for recursive references.", maxDepth, reader.Context.GetPath()),
				ErrorCode.SerializationGraphIsTooDeep)
			;
		}
		public static Exception SerializationGraphIsTooDeep(IJsonWriter writer, ulong maxDepth)
		{
			return new JsonSerializationException
			(
					string.Format("The serialization graph exceeds the maximum allowed depth ({0}) at path '{1}'. This often points to circular object references or very deep nesting. Consider increasing 'SerializationContext.MaxDepth' if this is intentional, or check for recursive references.", maxDepth, writer.Context.GetPath()),
				ErrorCode.SerializationGraphIsTooDeep)
			;
		}
		public static Exception CircularReferenceDetected(IJsonWriter writer, Type type)
		{
			return new JsonSerializationException
			(
				string.Format("A circular reference was detected while serializing an instance of type '{0}' at path '{1}'. This library does not support cyclic object graphs; break the cycle or exclude the back-reference member with an '[IgnoreDataMember]' attribute.", type.FullName, writer.Context.GetPath()),
				ErrorCode.CircularReferenceDetected
			);
		}
		public static Exception TypeIsNotValid(Type type, string problem)
		{
			problem = problem.TrimEnd('.');

			return new JsonSerializationException
			(
				string.Format("Type '{0}' is not valid for serialization: {1}.", type.Name, problem),
				ErrorCode.TypeIsNotValid
			);
		}
		public static Exception SerializingUnknownType(Type type)
		{
			return new JsonSerializationException
			(
				string.Format("Attempt to serialize unknown type '{0}' failed. This type might not be registered in 'Json.DefaultSerializers' or it may lack a suitable serializer. Ensure the type is supported or register a custom 'TypeSerializer' for it.", type.FullName),
				ErrorCode.SerializingUnknownType
			);
		}
		public static Exception SerializingSpecialSystemType(Type type)
		{
			return new JsonSerializationException
			(
				string.Format("Attempt to serialize special system type '{0}' failed. This type is restricted and cannot be serialized. This typically occurs when using low-level types like 'Pointer', 'RuntimeHandle', or 'IntPtr' in your data contract.", type.FullName),
				ErrorCode.SerializingSpecialSystemType
			);
		}
		public static Exception UnexpectedEndOfStream(IJsonReader reader, string context = null)
		{
			var message = context != null
				? string.Format("Unexpected end of stream while {0} at path '{1}'. The stream may be incomplete, closed prematurely, or in an invalid format.", context, reader.Context.GetPath())
				: string.Format("Unexpected end of stream while more data was expected at path '{0}'. This can happen if you forgot to rewind the stream, if the network stream is incomplete, or if the document is missing closing characters.", reader.Context.GetPath());
			return new JsonSerializationException(message, ErrorCode.UnexpectedEndOfStream, reader);
		}
		public static Exception UnexpectedMemberName(string memberName, string expected, IJsonReader reader)
		{
			return new JsonSerializationException
			(
				string.Format("Unexpected member '{0}' was read while '{1}' was expected at path '{2}'. Ensure that JSON member names match the target object's property names (case-sensitive) or use [DataMember(Name=...)] attribute.", memberName, expected, reader.Context.GetPath()),
				ErrorCode.UnexpectedMemberName,
				reader
			);
		}
		public static Exception UnexpectedToken(IJsonReader reader, params JsonToken[] expectedTokens)
		{
			return UnexpectedToken(reader, null, expectedTokens);
		}
		public static Exception UnexpectedToken(IJsonReader reader, Type expectedType, params JsonToken[] expectedTokens)
		{
			var tokensStr = default(string);
			if (expectedTokens == null || expectedTokens.Length == 0)
			{
				tokensStr = "<no tokens>";
			}
			else
			{
				var tokens = expectedTokens.Select(c =>
				{
					switch (c)
					{
						case JsonToken.BeginArray: return "[";
						case JsonToken.EndOfArray: return "]";
						case JsonToken.BeginObject: return "{";
						case JsonToken.EndOfObject: return "}";
						case JsonToken.Member: return "member name";
						case JsonToken.None:
						case JsonToken.Number:
						case JsonToken.StringLiteral:
						case JsonToken.DateTime:
						case JsonToken.Null:
						case JsonToken.Boolean:
						case JsonToken.EndOfStream:
						default: return c.ToString();
					}
				}).ToArray();
				tokensStr = string.Join(", ", tokens);
			}

			if (reader.Token == JsonToken.EndOfStream)
			{
				return UnexpectedEndOfStream(reader);
			}

			var typeInfo = expectedType != null ? string.Format(" for type '{0}'", expectedType.Name) : "";
			var advice = "";
			if (reader.Token == JsonToken.BeginObject && expectedTokens != null && expectedTokens.Contains(JsonToken.BeginArray))
				advice = " Found '{' instead of expected '['. Ensure input data is a collection.";
			else if (reader.Token == JsonToken.BeginArray && expectedTokens != null && expectedTokens.Contains(JsonToken.BeginObject))
				advice = " Found '[' instead of expected '{'. Ensure input data is a single object.";
			else if (reader.Token == JsonToken.Member && expectedTokens != null && (expectedTokens.Contains(JsonToken.StringLiteral) || expectedTokens.Contains(JsonToken.Number)))
				advice = " Found a member name but expected a value. Check for misplaced colons or incorrect nesting.";

			var message = expectedTokens != null && expectedTokens.Length > 1
				? string.Format("Unexpected token '{0}' was read while any of '{1}' were expected{2} at path '{3}'.{4}", reader.Token, tokensStr, typeInfo, reader.Context.GetPath(), advice)
				: string.Format("Unexpected token '{0}' was read while '{1}' was expected{2} at path '{3}'.{4}", reader.Token, tokensStr, typeInfo, reader.Context.GetPath(), advice);

			return new JsonSerializationException(message, ErrorCode.UnexpectedToken, reader);
		}
		public static Exception UnknownEscapeSequence(string escape, IJsonReader reader)
		{
			return new JsonSerializationException
			(
				string.Format("An unknown escape sequence '{0}' was encountered at path '{1}'. This typically indicates an invalid or non-standard JSON escape sequence. Ensure the JSON follows RFC 8259 standards for string escaping.", escape, reader.Context.GetPath()),
				ErrorCode.UnknownEscapeSequence,
				reader
			);
		}
		public static Exception SerializationFramesCorruption()
		{
			return new JsonSerializationException
			(
				"Serialization frames are corrupted. This is likely due to an invalid Push/Pop sequence in a TypeSerializer implementation.",
				ErrorCode.SerializationFramesCorruption
			);
		}
		public static Exception StreamIsNotReadable()
		{
			return new JsonSerializationException
			(
				"Cannot perform deserialization from a stream that does not support reading. Ensure the source stream is opened with 'FileAccess.Read' or equivalent access rights.",
				ErrorCode.StreamIsNotReadable
			);
		}
		public static Exception StreamIsNotWriteable()
		{
			return new JsonSerializationException
			(
				"Cannot perform serialization to a stream that does not support writing. Ensure the destination stream is opened with 'FileAccess.Write' or equivalent access rights.",
				ErrorCode.StreamIsNotWriteable
			);
		}
		public static Exception UnterminatedStringLiteral(IJsonReader reader)
		{
			return new JsonSerializationException
			(
				string.Format("An unterminated string literal was encountered at path '{0}'. This might be due to truncated JSON data or a missing closing double-quote at the end of a string.", reader.Context.GetPath()),
				ErrorCode.UnterminatedStringLiteral,
				reader
			);
		}
		public static Exception UnknownNotation(IJsonReader reader, string notation)
		{
			return new JsonSerializationException
			(
				string.Format("An unknown notation '{0}' was encountered at path '{1}'. The input data might be corrupted or contains syntax not supported by the JSON parser.", notation, reader.Context.GetPath()),
				ErrorCode.UnknownNotation,
				reader
			);
		}
		public static Exception TypeRequiresCustomSerializer(Type type, Type typeSerializer)
		{
			return new JsonSerializationException
			(
				string.Format("Type '{0}' can't be serialized by '{1}' and requires custom {2} registered in 'Json.DefaultSerializers'.", type.FullName, typeSerializer.Name, typeof(TypeSerializer).Name),
				ErrorCode.TypeRequiresCustomSerializer
			);
		}
		public static Exception FailedToReadDictionaryKey(IJsonReader reader, Type keyType, Exception innerException)
		{
			return new JsonSerializationException
			(
				string.Format("Failed to read dictionary key of type '{0}' at path '{1}': {2}\r\nMore detailed information in inner exception.", keyType.Name, reader.Context.GetPath(), innerException.Message),
				ErrorCode.FailedToReadDictionaryKey,
				reader,
				innerException
			);
		}
		public static Exception FailedToReadDictionaryValue(IJsonReader reader, Type valueType, object key, Exception innerException)
		{
			return new JsonSerializationException
			(
				string.Format("Failed to read dictionary value of type '{0}' for key '{1}' at path '{2}': {3}\r\nMore detailed information in inner exception.", valueType.Name, key ?? "<unknown>", reader.Context.GetPath(), innerException.Message),
				ErrorCode.FailedToReadDictionaryValue,
				reader,
				innerException
			);
		}
		public static Exception UnsupportedMemberType(MemberInfo member)
		{
			return new JsonSerializationException
			(
				string.Format("Member '{0}' has an unsupported reflection type '{1}'. Only properties and fields can be used as data members.", member.Name, member.MemberType),
				ErrorCode.UnsupportedMemberType
			);
		}
		public static Exception CantSerializeDelegateType(Type type)
		{
			return new JsonSerializationException
			(
				string.Format("Unable to serialize delegate type '{0}'. Delegates reference executable code and cannot be represented in JSON or MessagePack.", type),
				ErrorCode.CantSerializeDelegateType
			);
		}
		public static Exception MemberIsWriteOnly(string memberName)
		{
			return new JsonSerializationException
			(
				string.Format("Member '{0}' is write-only and cannot be read during serialization.", memberName),
				ErrorCode.MemberIsWriteOnly
			);
		}
		public static Exception MemberIsReadOnly(string memberName)
		{
			return new JsonSerializationException
			(
				string.Format("Member '{0}' is read-only and cannot be set during deserialization.", memberName),
				ErrorCode.MemberIsReadOnly
			);
		}
		public static Exception FailedToResolveMemberType(IJsonReader reader, string typeName, string memberName, Type objectType, Exception innerException)
		{
			return new JsonSerializationException
			(
				string.Format("Failed to resolve type '{0}' of value for member '{1}' of type '{2}' at path '{3}'.\r\nMore detailed information in inner exception.", typeName, memberName, objectType.Name, reader.Context.GetPath()),
				ErrorCode.FailedToResolveMemberType,
				reader,
				innerException
			);
		}
		public static Exception FailedToReadMemberValue(IJsonReader reader, string memberName, Type objectType, Exception innerException)
		{
			return new JsonSerializationException
			(
				string.Format("Failed to read value for member '{0}' of type '{1}' at path '{2}'.\r\nMore detailed information in inner exception.", memberName, objectType.Name, reader.Context.GetPath()),
				ErrorCode.FailedToReadMemberValue,
				reader,
				innerException
			);
		}
		public static Exception FailedToSetMemberValue(string memberName, object value, Exception innerException)
		{
			return new JsonSerializationException
			(
				string.Format("Failed to set member '{0}' to value '{1}' of type {2}.\r\nMore detailed information in inner exception.", memberName, value, value != null ? value.GetType().FullName : "<null>"),
				ErrorCode.FailedToSetMemberValue,
				null,
				innerException
			);
		}
		public static Exception FailedToParseDateTime(IJsonReader reader, string dateTimeStr, string pattern, Exception innerException)
		{
			return new JsonSerializationException
			(
				string.Format("Failed to parse date '{0}' with pattern '{1}' at path '{2}'.", dateTimeStr, pattern, reader.Context.GetPath()),
				ErrorCode.FailedToParseDateTime,
				reader,
				innerException
			);
		}
	}
}
